---
version: '3.5'

services:
#  nginx:
#    build:
#      context: .
#      dockerfile: nginx/Dockerfile
#    ports:
#      - 80:80

  web:
    build:
      context: ""
      dockerfile: Dockerfile
    environment:
      - ACCESS_KEY_ID=
      - ACCESS_SECRET_KEY=
    env_file:
      - vars.env
    ports:
      - 8080:8080
    command: ["./main"]