---
version: '3.5'

services:
  website-dev:
    build:
      context: .
      dockerfile: build/dev/Dockerfile
    container_name: website-dev
    env_file:
      - vars.env
    ports:
      - '8080:8080'
    volumes:
      - './pkg/website:/go/src/pogzyb/website:z'
      - './web:/app/web:z'

  website-aws:
    build:
      context: .
      dockerfile: build/aws/Dockerfile
    container_name: website-aws
    env_file:
      - vars.env
    ports:
      - '8080:8080'
